modLoader="kotlinforforge"
loaderVersion="[1.12,)"
#issueTrackerURL = ""
license = "Apache-2.0"

[[mods]]
modId = "mountainous"
version = "${version}"
displayName = "Mountainous"
authors = "Skyternity Modding Group"
description = '''
A Mod which aims to expands the mountains a little in a vanilla fashion.
'''
#logoFile = ""

[[dependencies.mountainous]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mountainous]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mountainous]]
modId = "architectury"
mandatory = true
versionRange = "[1.1.55,)"
ordering = "AFTER"
side = "BOTH"

